module.exports = {
  apps: [
    {
      name: 'DBW_FP',
      script: './bin/www.js',
      // args: 'one two',
      // instances: 0,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      ignore_watch: [
        'package-lock.json',
        '**/*/package-lock.json',
        '**/node_modules/',
        '**/log/',
        '**/.vscode/',
        '**/out/',
        '**/docs/',
        '**/snapshot/',
        '**/dist/',
        '*.log',
      ],
      env: {
        NODE_ENV: 'development',
        PJ_MAIN_ID: 'FP',
        PJ_HTTP_PORT: 7600,
        PJ_API_PORT: 7510,
        PJ_DB_HOST: 'localhost',
        PJ_DB_PORT: 9000,
        PJ_DB_DB: 'FARM_PARALLEL',
        PJ_DB_USER: 'root',
        PJ_DB_PW: 'smsoftware',
      },
      env_production: {
        NODE_ENV: 'production',
      },
    },
    {
      name: 'DBW_S2W',
      script: './bin/www.js',
      // instances: 0,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      // wait_ready: true,
      // listen_timeout: 50000,
      // kill_timeout: 5000,
      ignore_watch: [
        'package-lock.json',
        '**/*/package-lock.json',
        '**/node_modules/',
        '**/log/',
        '**/.vscode/',
        '**/out/',
        '**/docs/',
        '**/snapshot/',
        '**/dist/',
        '*.log',
      ],
      env: {
        NODE_ENV: 'development',
        PJ_MAIN_ID: 'S2W',
        PJ_HTTP_PORT: 7601,
        PJ_API_PORT: 7511,
        // DB
        PJ_DB_HOST: 'localhost',
        PJ_DB_PORT: 9000,
        PJ_DB_DB: 'SOLAR_2WAY',
        PJ_DB_USER: 'solar2way',
        PJ_DB_PW: 'qwer1234',
      },
      env_production: {
        NODE_ENV: 'production',
      },
    },
  ],

  deploy: {
    production: {
      user: 'node',
      host: '212.83.163.1',
      ref: 'origin/master',
      repo: 'git@github.com:repo.git',
      path: '/var/www/production',
      'post-deploy': 'npm install && pm2 reload ecosystem.config.js --env production',
    },
  },
};
